
;INSTRUCTIONS;

.orig x3000

LD R1, DEC_1		;DECIMAL UNO
LD R5, ARRAY_POINTER	;THE POINTER
LD R4, DEC_10		;DECIMAL 10


WHILE_LOOP
	STR R1, R5, #0		;STORES THE VALUES
	ADD R5, R5, #1		;IN THE ARRAY
	ADD R1, R1, R1		;WILL KEEP STORING
	ADD R4, R4, #-1		;NO MATTER WHAT THE SIGN
	BRnp WHILE_LOOP

LD R5, DEC_10
LD R2, ARRAY_POINTER

TWO_WHILE_LOOP			;WILL ITERATE THROUGH THE ARRAY
 LDR R1, R2, #0
 LD R6, DEC_FOUR
 LD R3, STORAGE_VAL		
 ST R2, ARRAY_POINTER		;STORE THE POINTER TO ACCESS IT LATER
 LD R2, DEC_16			;OUPUT ONLY UNTIL 16
 
;OUTPUTTING THE B FOR BINARY
;NOT BRANCHED OUT BECAUSE WE ONLY NEED TO PRINT IT ONCE BEFORE EACH BIN NUM
LD R0, CHAR_B
OUT

;PRINTING THE ACTUAL ARRAY
THIRD_LOOP_PRINT
 AND R4, R1, R3			;WILL AND R1 AND R3 AND PUT IN R4
 NOT R4, R4			;2'S COMPLEMENT 
 ADD R4, R4, #1			;AGAIN 2'S COMPLEMENT
 ADD R4, R3, R4			;ADD R4 AND THE R3 AND PUT INTO R4 AGAIN
 BRnp NUM_ZERO

 NUM_ONE
	LD R0, DEC_ONE
	OUT
	BR FINISHING_FUNC
 NUM_ZERO
	LD R0, DEC_ZERO
	OUT
	BR FINISHING_FUNC

 FINISHING_FUNC
	;COUNT UP TO 4 NUMBERS THEN OUTPUT THE UNIVERSE XD
  ADD R6, R6, #-1		;COUNTER
  BRnp NO_SPACES		;JUST GO TO NO SPACE UNTIL 0

 LD R0, NEW_SPACE		;NOW OUTPUT SPACE WHEN 0
 OUT				;OUTPUTTING

 LD R6, DEC_FOUR		;GO 4 NUMS
 NO_SPACES

 ADD R1, R1, R1
 ADD R2, R2, #-1
 BRnp THIRD_LOOP_PRINT

LD R0, NEW_LINE			;PUT OUT THE NEWLINE AFTER EACH 16 BITS+1b
OUT
ADD R5, R5, #-1

LD R2, ARRAY_POINTER		;RE-PUT THE POINTER INTO R2
ADD R2, R2, #1
ST R2, ARRAY_POINTER		;INCREASE R2 BY 1 AND PUT PNTR TO R2
ADD R5, R5, #0			;CHECKING ZEROES
BRnp TWO_WHILE_LOOP

HALT

;=========
;DATA;
;=========

DEC_1		.FILL #1
DEC_10		.FILL #10
ARRAY_POINTER	.FILL x4000
CHAR_B		.FILL 'b'

DEC_ZERO	.FILL x30
DEC_ONE		.FILL x31
NEW_SPACE	.FILL x20	;CAN DO FILL x20 ALSO
DEC_FOUR	.FILL	#4

DEC_16		.FILL	#16
STORAGE_VAL	.FILL	x8000
NEW_LINE	.FILL	xA	;CAN DO STRINGZ '\N' ALSO


;=========
;REMOTE DATA;
;=========

.ORIG x4000
ARRAY .BLKW	#10

.end